# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HVg8hjTfhXoRaH1OE-X2smYEIea2YcOE
"""

# Sistema de Cadastro Simples
# Autor: Ernany Verruck
# Descrição: Programa para cadastrar, listar e remover pessoas

pessoas = []

while True:
    print("\n=== MENU ===")
    print("1 - Cadastrar pessoa")
    print("2 - Listar pessoas")
    print("3 - Remover pessoa")
    print("0 - Sair")

    opcao = input("Escolha uma opção: ")

    if opcao == "1":
        nome = input("Digite o nome: ")
        idade = input("Digite a idade: ")

        if nome == "" or idade == "":
            print("Nome e idade não podem ser vazios.")
        else:
            pessoas.append([nome, idade])
            print("Pessoa cadastrada com sucesso!")

    elif opcao == "2":
        if len(pessoas) == 0:
            print("Nenhuma pessoa cadastrada.")
        else:
            print("\nPessoas cadastradas:")
            for pessoa in pessoas:
                print(f"Nome: {pessoa[0]} | Idade: {pessoa[1]}")

    elif opcao == "3":
        nome = input("Digite o nome da pessoa para remover: ")
        encontrado = False

        for pessoa in pessoas:
            if pessoa[0] == nome:
                pessoas.remove(pessoa)
                encontrado = True
                print("Pessoa removida com sucesso!")
                break

        if not encontrado:
            print("Pessoa não encontrada.")

    elif opcao == "0":
        print("Saindo do programa...")
        break

    else:
        print("Opção inválida. Tente novamente.")